# This file is part of the Sylius package.
# (c) Paweł Jędrzejewski

sylius_mailer:
    emails:
        api_verification_token:
            subject: sylius.emails.user.verification_token.subject
            template: "ShopApiPlugin:Email:verification.html.twig"
        api_reset_password_token:
            subject: sylius.emails.user.reset_password_token.subject
            template: "ShopApiPlugin:Email:passwordReset.html.twig"
        api_order_pay_payment_error:
            subject: sylius.emails.order.checkout_pay_payment_error
            template: "ShopApiPlugin:Email:payPaymentError.html.twig"
